//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFGExamAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationStatu()
        {
            this.RegisteredCourses = new HashSet<RegisteredCourse>();
        }
    
        public int RegistrationStatusID { get; set; }
        public string RegistrationStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredCourse> RegisteredCourses { get; set; }
    }
}
