//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFGExamAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredCourse
    {
        public int RegisteredCourseID { get; set; }
        public Nullable<int> LearnerID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<int> RegistrationStatusID { get; set; }
        public Nullable<System.DateTime> DeregisterDate { get; set; }
        public string DeregisterReason { get; set; }
        public Nullable<double> LearnerMark { get; set; }
        public string CourseComments { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Learner Learner { get; set; }
        public virtual RegistrationStatu RegistrationStatu { get; set; }
    }
}
